{% set version = "2.10-12" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-liblinear
  version: {{ version|replace("-", "_") }}

source:
  fn: LiblineaR_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/LiblineaR_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/LiblineaR/LiblineaR_{{ version }}.tar.gz

  sha256: 3ae337909c552ae8880322f74dc90a5a32ec9b5e2012382be5d43db7e85cbd64

build:
  merge_build_host: true  # [win]
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('LiblineaR')"  # [not win]
    - "\"%R%\" -e \"library('LiblineaR')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/LiblineaR/index.html
  license: GPL-2
  summary: A wrapper around the LIBLINEAR C/C++ library for machine learning.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
