travis:
  secure:
    BINSTAR_TOKEN: DFYG7I1ex1gNU3dXTzota9SSn7k0TYhGM9E7F3vkx3K1z7IjzRGtn9gIqhtZ7InRurtcAuVkLfE0pw6YmnykvayvwS/VZ6RBBu4U2kg7qy7lrBxltirwtNedB2eR99MI7S31iGyDiD3jaDZKnY+0dfdcYbQLFX6FhQJpmY94cQ6VDv4KjNyo96sTSjfFZYTzsKjRw2V8FeBdl3yNpakK+NQ5ArSFk9ZfkewgLWkUJlm7FM3XeOGnq5ZO0ImvHoRfsMf6nCBAdSruI86riQgp2qJ8cIKI7KxKpdrzWWQNV7CSsxWfTWCk/g4PBcaX7iprL6Ai/KzD+QIoPX0berMhJ4VEUHVFB1JfqKO1HgxkCH4Dcx2yQjltZ70vK4dITycg0zcFKTo+QhmUUq0YjXgn+z3o4zDtlXpyc42WvDsVfI/JSL2uT00uiOhc7pmbAEru+8YAbqyMj9AprQudU9hHMEsz3HdzXWkXawZKBPzZLOnlNZbv3xGl1Rmj0AAhneU0gdwKAMBqGGNxU1AfADpBex0sdYino2WLs+AMggqyYaGWTPRxuHzN7M5lGsVOXz9QmTPpd8BCEgldgwGMHdXk5MSa/9xSiAE8J/2srGof+ePgllZxMdOpVjdd3krg64JANlB+NloShH41cLm8k1weK/b3UMfaHA96cvohCaLW2bk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
