appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: LjXi5aZRrKitNiXF86N2I16fKtX1pDslw0NT+kw4XEAxVs8r8+9vxjDZ3r+RnKnSVNRBhX8I5qM3e3MjXWTiYDLkHIeLbdyQr/PXZkXkypgsbuV36QAbW1G2efB39aR1T0dC8nzmnneTb6yWGy0n9GxIF58HIpUx29CSo83o6IHYGT/HBsk45sKQatZ+T7jmIyIsJVil9LywcHe+i1/qURBt8zkS3/z+kIPalYRkrQbWSE7Wlpc5odxlO27EOUFkCHEhK4MweUF77+bV3waqMJpZA3Sx19LCBR+FIGBD3g0w8TK4mVDw/GhadKganMxGnLmMRLwAniq2TWvrCzJtED6iZEjBYLdW7y06XWhxytJy6VoMdgs1vuEawGH6LwGZHy1qgElFek6N5dSB233D8egRWcq4RmeeCsbk30iRTX9VHZWu3wFs8yqBp24PKxfai0ZF2q61wXzQWKqAjQvWfgZsjK+5LrCuj/dtjrqH6Tvh2OVFxAichySn2Z1t5IpdmWa/MKG9iwOxLFw4WTJD9CJwAbn6WpnmE8G5B7XyRAaEL8ihg385N494VarJH3RdV5yaj9aZGgaKoQYkfLXsMmfFSFycMC4uDGts1miHKEoSZRImYXOhWrkDxH6i7rU59TXuvbz+mIrEdOH1auLEZ3UPtj5ns2shUy3flVYj8uE=}
