travis:
  secure:
    BINSTAR_TOKEN: d04QXBs9BHbnr+b2GXuh7+V7l/6G+qwAsp/EeO/xVPCqTvU28TKs4fR4FE7hLLNRqiCaMaAH80HY8v9P5kE/b02VJx9Ew7PmKrMHTDRWugBZNXNxjbg6clBG4chVdekBYprD30aFt8hrcG+XWWZcB8dHJGlOaujJqSBchjYNKX8UeOX1D3tkB66ZB3X7yaviWnFPjaov9w6g2P8mo658AzwNjWEkvIxekEyhWP3Mg2IvykE7eEt8eA/h7k5cpygmjp/VzHZwbZzla5ZK2w7hF8Ub4yFGod/ZUY145iAnrj04GKYz8y6uI+1Jnh6iG5iaah0yAF8cePYyPz3p6D+Pd1dZnX/tswT14G8iUiMXE/aE39SyTW0WZW57CyvQj+G0PielBBtvmBx7KlHLP2aiOZlEgon/Klk0GKZeR+UBdCcLEPEA1TW89/g2BfBJhZkvyJwqlrHt/UHoKdzZ501v3HrbJftW+w04JKXKzqNeU9HUqiRBDE0BwpZ2mKs/rPc21+ZLmrFXkqtXb1w9im1NRynvkS+dzWY25btgSq3qPViQC1T5DHXxnA44a2IQS0Qqnq1EZHgvIdzQTJuJ7kO+ZA7vCVBMo07VIZmn7lNBcNdZpSmvQinuw/7NMkwOMt2uRpvKTuFh/Lff/p8D5HZxDS10w1vzNEqofpEmOIGvWc4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
